external_components:
  - source: 
      type: git
      url: https://github.com/nic6911/esphome_components
      ref: feature/ahc9000v2update
    refresh: 0s
    components: [wavinahc9000v2]

wavinahc9000v2:
